var nam = 'Thiago';
let surname = 'Frank';
const key = true;

function test(){
    let surname;

    if (key){
        surname = 'Almeida';
    }

    console.log(surname);
}

console.log(nam);
test();

//Test in another example, generated by AI, comments are mine

function exemploVar() {
    if (true) {
      var x = 10;
      console.log(x); // Vai printar o valor da variável
    }
    console.log(x); //  Mesmo que VAR X esteja no escopo do if, ele consegue escapar por ser uma tipagem global.
  }

  console.log(x); //Mas aqui ela não vai funcionar, pois o JS tranca suas funções de modo especial
  //Erro: x is not defined
  exemploVar();
  
  //Test checked, as waited an error has ocurred!!
//------------------------------------------------------------------------------------------------------------------


//Test in another example, generated by AI, comments are mine.

function exemploLet() {
    if (true) {
      let y = 20;
      console.log(y); // Saída: 20
    }
     console.log(y); // Erro: y não está definido neste escopo. O let só possui poder dentro do escopo.
     //Para melhor controle das minha variáveis, é melhor usar let que que var
  }
  exemploLet();
  



